# Generated by Django 4.2.11 on 2024-11-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст'),
        ),
    ]
